<Start>
 <ADecVaretfctProgram>
  <ADecVariablesOptdecvar>
   <ADeclarerVariableListedecvar>
    <ADecvarEntierDecvar>
    </ADecvarEntierDecvar>
   </ADeclarerVariableListedecvar>
  </ADecVariablesOptdecvar>
  <AListedecfoncRecListedecfonc>
   <AInstrDecfonc>
    <ASansparamListeparam>
    </ASansparamListeparam>
    <AInstrbloc>
     <ALinstrecListeinst>
      <AInstraffectInstr>
       <AInstraffect>
        <AVarsimpleVar>
        </AVarsimpleVar>
        <ASimpleExpr>
         <ASimpleExprOu>
          <ASimpleExprEt>
           <ASimpleExprEgal>
            <ASimpleExprPlus>
             <ASimpleExprMult>
              <ANombreExprComplete>
              </ANombreExprComplete>
             </ASimpleExprMult>
            </ASimpleExprPlus>
           </ASimpleExprEgal>
          </ASimpleExprEt>
         </ASimpleExprOu>
        </ASimpleExpr>
       </AInstraffect>
      </AInstraffectInstr>
      <ALinstrecListeinst>
       <AInstrecritureInstr>
        <AInstrwrite>
         <ASimpleExpr>
          <ASimpleExprOu>
           <ASimpleExprEt>
            <ASimpleExprEgal>
             <ASimpleExprPlus>
              <ASimpleExprMult>
               <AVarExprComplete>
                <AVarsimpleVar>
                </AVarsimpleVar>
               </AVarExprComplete>
              </ASimpleExprMult>
             </ASimpleExprPlus>
            </ASimpleExprEgal>
           </ASimpleExprEt>
          </ASimpleExprOu>
         </ASimpleExpr>
        </AInstrwrite>
       </AInstrecritureInstr>
       <ALinstfinalListeinst>
       </ALinstfinalListeinst>
      </ALinstrecListeinst>
     </ALinstrecListeinst>
    </AInstrbloc>
   </AInstrDecfonc>
   <AListedecfoncFinalListedecfonc>
   </AListedecfoncFinalListedecfonc>
  </AListedecfoncRecListedecfonc>
 </ADecVaretfctProgram>
</Start>
