<Start>
 <ADecFctProgram>
  <AListedecfoncRecListedecfonc>
   <AInstrDecfonc>
    <ASansparamListeparam>
    </ASansparamListeparam>
    <AInstrbloc>
     <ALinstrecListeinst>
      <AInstrecritureInstr>
       <AInstrwrite>
        <ASimpleExpr>
         <ASimpleExprOu>
          <ASimpleExprEt>
           <APlusExprEgal>
            <APlusExprEgal>
             <ASimpleExprEgal>
              <ASimpleExprPlus>
               <ASimpleExprMult>
                <ANombreExprComplete>
                </ANombreExprComplete>
               </ASimpleExprMult>
              </ASimpleExprPlus>
             </ASimpleExprEgal>
             <ASimpleExprPlus>
              <ASimpleExprMult>
               <ANombreExprComplete>
               </ANombreExprComplete>
              </ASimpleExprMult>
             </ASimpleExprPlus>
            </APlusExprEgal>
            <ASimpleExprPlus>
             <ASimpleExprMult>
              <ANombreExprComplete>
              </ANombreExprComplete>
             </ASimpleExprMult>
            </ASimpleExprPlus>
           </APlusExprEgal>
          </ASimpleExprEt>
         </ASimpleExprOu>
        </ASimpleExpr>
       </AInstrwrite>
      </AInstrecritureInstr>
      <ALinstfinalListeinst>
      </ALinstfinalListeinst>
     </ALinstrecListeinst>
    </AInstrbloc>
   </AInstrDecfonc>
   <AListedecfoncFinalListedecfonc>
   </AListedecfoncFinalListedecfonc>
  </AListedecfoncRecListedecfonc>
 </ADecFctProgram>
</Start>
