<Start>
 <ADecFctProgram>
  <AListedecfoncRecListedecfonc>
   <AInstrDecfonc>
    <AAvecparamListeparam>
     <ADeclarationVariablesMultiplesListedecvar>
      <ADecvarEntierDecvar>
      </ADecvarEntierDecvar>
      <ALastListedecvarChainee>
       <ADecvarEntierDecvar>
       </ADecvarEntierDecvar>
      </ALastListedecvarChainee>
     </ADeclarationVariablesMultiplesListedecvar>
    </AAvecparamListeparam>
    <AInstrbloc>
     <ALinstrecListeinst>
      <AInstrretourInstr>
       <AInstrreturn>
        <ASimpleExpr>
         <ASimpleExprOu>
          <ASimpleExprEt>
           <ASimpleExprEgal>
            <ASimpleExprPlus>
             <ASimpleExprMult>
              <AParenthesesExprComplete>
               <ASimpleExpr>
                <ASimpleExprOu>
                 <ASimpleExprEt>
                  <ASimpleExprEgal>
                   <ASimpleExprPlus>
                    <ASimpleExprMult>
                     <AVarExprComplete>
                      <AVarsimpleVar>
                      </AVarsimpleVar>
                     </AVarExprComplete>
                    </ASimpleExprMult>
                   </ASimpleExprPlus>
                  </ASimpleExprEgal>
                 </ASimpleExprEt>
                </ASimpleExprOu>
               </ASimpleExpr>
              </AParenthesesExprComplete>
             </ASimpleExprMult>
            </ASimpleExprPlus>
           </ASimpleExprEgal>
          </ASimpleExprEt>
         </ASimpleExprOu>
        </ASimpleExpr>
       </AInstrreturn>
      </AInstrretourInstr>
      <ALinstfinalListeinst>
      </ALinstfinalListeinst>
     </ALinstrecListeinst>
    </AInstrbloc>
   </AInstrDecfonc>
   <AListedecfoncRecListedecfonc>
    <AInstrDecfonc>
     <ASansparamListeparam>
     </ASansparamListeparam>
     <AInstrbloc>
      <ALinstrecListeinst>
       <AInstrecritureInstr>
        <AInstrwrite>
         <ASimpleExpr>
          <ASimpleExprOu>
           <ASimpleExprEt>
            <ASimpleExprEgal>
             <ASimpleExprPlus>
              <ASimpleExprMult>
               <AAppelfctExprComplete>
                <AAvecparamAppelfct>
                 <AElementsmultiplesListexpr>
                  <ASimpleExpr>
                   <ASimpleExprOu>
                    <ASimpleExprEt>
                     <ASimpleExprEgal>
                      <ASimpleExprPlus>
                       <ASimpleExprMult>
                        <ANombreExprComplete>
                        </ANombreExprComplete>
                       </ASimpleExprMult>
                      </ASimpleExprPlus>
                     </ASimpleExprEgal>
                    </ASimpleExprEt>
                   </ASimpleExprOu>
                  </ASimpleExpr>
                  <AElementsmultiplesListexprChainee>
                   <ASimpleExpr>
                    <ASimpleExprOu>
                     <ASimpleExprEt>
                      <ASimpleExprEgal>
                       <ASimpleExprPlus>
                        <ASimpleExprMult>
                         <ANombreExprComplete>
                         </ANombreExprComplete>
                        </ASimpleExprMult>
                       </ASimpleExprPlus>
                      </ASimpleExprEgal>
                     </ASimpleExprEt>
                    </ASimpleExprOu>
                   </ASimpleExpr>
                   <AVideListexprChainee>
                   </AVideListexprChainee>
                  </AElementsmultiplesListexprChainee>
                 </AElementsmultiplesListexpr>
                </AAvecparamAppelfct>
               </AAppelfctExprComplete>
              </ASimpleExprMult>
             </ASimpleExprPlus>
            </ASimpleExprEgal>
           </ASimpleExprEt>
          </ASimpleExprOu>
         </ASimpleExpr>
        </AInstrwrite>
       </AInstrecritureInstr>
       <ALinstfinalListeinst>
       </ALinstfinalListeinst>
      </ALinstrecListeinst>
     </AInstrbloc>
    </AInstrDecfonc>
    <AListedecfoncFinalListedecfonc>
    </AListedecfoncFinalListedecfonc>
   </AListedecfoncRecListedecfonc>
  </AListedecfoncRecListedecfonc>
 </ADecFctProgram>
</Start>
