/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class AAppelfctExprComplete extends PExprComplete
{
    private PAppelfct _appelfct_;

    public AAppelfctExprComplete()
    {
        // Constructor
    }

    public AAppelfctExprComplete(
        @SuppressWarnings("hiding") PAppelfct _appelfct_)
    {
        // Constructor
        setAppelfct(_appelfct_);

    }

    @Override
    public Object clone()
    {
        return new AAppelfctExprComplete(
            cloneNode(this._appelfct_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAppelfctExprComplete(this);
    }

    public PAppelfct getAppelfct()
    {
        return this._appelfct_;
    }

    public void setAppelfct(PAppelfct node)
    {
        if(this._appelfct_ != null)
        {
            this._appelfct_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._appelfct_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._appelfct_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._appelfct_ == child)
        {
            this._appelfct_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._appelfct_ == oldChild)
        {
            setAppelfct((PAppelfct) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
