/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class ADecvarEntierDecvar extends PDecvar
{
    private TInt _int_;
    private TIdentificator _identificator_;

    public ADecvarEntierDecvar()
    {
        // Constructor
    }

    public ADecvarEntierDecvar(
        @SuppressWarnings("hiding") TInt _int_,
        @SuppressWarnings("hiding") TIdentificator _identificator_)
    {
        // Constructor
        setInt(_int_);

        setIdentificator(_identificator_);

    }

    @Override
    public Object clone()
    {
        return new ADecvarEntierDecvar(
            cloneNode(this._int_),
            cloneNode(this._identificator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecvarEntierDecvar(this);
    }

    public TInt getInt()
    {
        return this._int_;
    }

    public void setInt(TInt node)
    {
        if(this._int_ != null)
        {
            this._int_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._int_ = node;
    }

    public TIdentificator getIdentificator()
    {
        return this._identificator_;
    }

    public void setIdentificator(TIdentificator node)
    {
        if(this._identificator_ != null)
        {
            this._identificator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identificator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._int_)
            + toString(this._identificator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._int_ == child)
        {
            this._int_ = null;
            return;
        }

        if(this._identificator_ == child)
        {
            this._identificator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._int_ == oldChild)
        {
            setInt((TInt) newChild);
            return;
        }

        if(this._identificator_ == oldChild)
        {
            setIdentificator((TIdentificator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
