/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class AInstrretourInstr extends PInstr
{
    private PInstrreturn _instrreturn_;

    public AInstrretourInstr()
    {
        // Constructor
    }

    public AInstrretourInstr(
        @SuppressWarnings("hiding") PInstrreturn _instrreturn_)
    {
        // Constructor
        setInstrreturn(_instrreturn_);

    }

    @Override
    public Object clone()
    {
        return new AInstrretourInstr(
            cloneNode(this._instrreturn_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstrretourInstr(this);
    }

    public PInstrreturn getInstrreturn()
    {
        return this._instrreturn_;
    }

    public void setInstrreturn(PInstrreturn node)
    {
        if(this._instrreturn_ != null)
        {
            this._instrreturn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instrreturn_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instrreturn_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instrreturn_ == child)
        {
            this._instrreturn_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instrreturn_ == oldChild)
        {
            setInstrreturn((PInstrreturn) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
