/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class AInstrecritureInstr extends PInstr
{
    private PInstrwrite _instrwrite_;

    public AInstrecritureInstr()
    {
        // Constructor
    }

    public AInstrecritureInstr(
        @SuppressWarnings("hiding") PInstrwrite _instrwrite_)
    {
        // Constructor
        setInstrwrite(_instrwrite_);

    }

    @Override
    public Object clone()
    {
        return new AInstrecritureInstr(
            cloneNode(this._instrwrite_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstrecritureInstr(this);
    }

    public PInstrwrite getInstrwrite()
    {
        return this._instrwrite_;
    }

    public void setInstrwrite(PInstrwrite node)
    {
        if(this._instrwrite_ != null)
        {
            this._instrwrite_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instrwrite_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instrwrite_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instrwrite_ == child)
        {
            this._instrwrite_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instrwrite_ == oldChild)
        {
            setInstrwrite((PInstrwrite) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
