/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class AInstrtantqueInstr extends PInstr
{
    private PInstrwhile _instrwhile_;

    public AInstrtantqueInstr()
    {
        // Constructor
    }

    public AInstrtantqueInstr(
        @SuppressWarnings("hiding") PInstrwhile _instrwhile_)
    {
        // Constructor
        setInstrwhile(_instrwhile_);

    }

    @Override
    public Object clone()
    {
        return new AInstrtantqueInstr(
            cloneNode(this._instrwhile_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstrtantqueInstr(this);
    }

    public PInstrwhile getInstrwhile()
    {
        return this._instrwhile_;
    }

    public void setInstrwhile(PInstrwhile node)
    {
        if(this._instrwhile_ != null)
        {
            this._instrwhile_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instrwhile_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instrwhile_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instrwhile_ == child)
        {
            this._instrwhile_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instrwhile_ == oldChild)
        {
            setInstrwhile((PInstrwhile) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
