/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class AInstrvideInstr extends PInstr
{
    private PInstrvoid _instrvoid_;

    public AInstrvideInstr()
    {
        // Constructor
    }

    public AInstrvideInstr(
        @SuppressWarnings("hiding") PInstrvoid _instrvoid_)
    {
        // Constructor
        setInstrvoid(_instrvoid_);

    }

    @Override
    public Object clone()
    {
        return new AInstrvideInstr(
            cloneNode(this._instrvoid_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstrvideInstr(this);
    }

    public PInstrvoid getInstrvoid()
    {
        return this._instrvoid_;
    }

    public void setInstrvoid(PInstrvoid node)
    {
        if(this._instrvoid_ != null)
        {
            this._instrvoid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instrvoid_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instrvoid_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instrvoid_ == child)
        {
            this._instrvoid_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instrvoid_ == oldChild)
        {
            setInstrvoid((PInstrvoid) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
