/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleExprOu extends PExprOu
{
    private PExprEt _exprEt_;

    public ASimpleExprOu()
    {
        // Constructor
    }

    public ASimpleExprOu(
        @SuppressWarnings("hiding") PExprEt _exprEt_)
    {
        // Constructor
        setExprEt(_exprEt_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleExprOu(
            cloneNode(this._exprEt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleExprOu(this);
    }

    public PExprEt getExprEt()
    {
        return this._exprEt_;
    }

    public void setExprEt(PExprEt node)
    {
        if(this._exprEt_ != null)
        {
            this._exprEt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprEt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprEt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprEt_ == child)
        {
            this._exprEt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprEt_ == oldChild)
        {
            setExprEt((PExprEt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
