/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleExprPlus extends PExprPlus
{
    private PExprMult _exprMult_;

    public ASimpleExprPlus()
    {
        // Constructor
    }

    public ASimpleExprPlus(
        @SuppressWarnings("hiding") PExprMult _exprMult_)
    {
        // Constructor
        setExprMult(_exprMult_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleExprPlus(
            cloneNode(this._exprMult_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleExprPlus(this);
    }

    public PExprMult getExprMult()
    {
        return this._exprMult_;
    }

    public void setExprMult(PExprMult node)
    {
        if(this._exprMult_ != null)
        {
            this._exprMult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprMult_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprMult_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprMult_ == child)
        {
            this._exprMult_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprMult_ == oldChild)
        {
            setExprMult((PExprMult) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
