/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleExprEgal extends PExprEgal
{
    private PExprPlus _exprPlus_;

    public ASimpleExprEgal()
    {
        // Constructor
    }

    public ASimpleExprEgal(
        @SuppressWarnings("hiding") PExprPlus _exprPlus_)
    {
        // Constructor
        setExprPlus(_exprPlus_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleExprEgal(
            cloneNode(this._exprPlus_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleExprEgal(this);
    }

    public PExprPlus getExprPlus()
    {
        return this._exprPlus_;
    }

    public void setExprPlus(PExprPlus node)
    {
        if(this._exprPlus_ != null)
        {
            this._exprPlus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprPlus_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprPlus_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprPlus_ == child)
        {
            this._exprPlus_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprPlus_ == oldChild)
        {
            setExprPlus((PExprPlus) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
