/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class AAvecparamAppelfct extends PAppelfct
{
    private TIdentificator _identificator_;
    private TLPar _lPar_;
    private PListexpr _listexpr_;
    private TRPar _rPar_;

    public AAvecparamAppelfct()
    {
        // Constructor
    }

    public AAvecparamAppelfct(
        @SuppressWarnings("hiding") TIdentificator _identificator_,
        @SuppressWarnings("hiding") TLPar _lPar_,
        @SuppressWarnings("hiding") PListexpr _listexpr_,
        @SuppressWarnings("hiding") TRPar _rPar_)
    {
        // Constructor
        setIdentificator(_identificator_);

        setLPar(_lPar_);

        setListexpr(_listexpr_);

        setRPar(_rPar_);

    }

    @Override
    public Object clone()
    {
        return new AAvecparamAppelfct(
            cloneNode(this._identificator_),
            cloneNode(this._lPar_),
            cloneNode(this._listexpr_),
            cloneNode(this._rPar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAvecparamAppelfct(this);
    }

    public TIdentificator getIdentificator()
    {
        return this._identificator_;
    }

    public void setIdentificator(TIdentificator node)
    {
        if(this._identificator_ != null)
        {
            this._identificator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identificator_ = node;
    }

    public TLPar getLPar()
    {
        return this._lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(this._lPar_ != null)
        {
            this._lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lPar_ = node;
    }

    public PListexpr getListexpr()
    {
        return this._listexpr_;
    }

    public void setListexpr(PListexpr node)
    {
        if(this._listexpr_ != null)
        {
            this._listexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listexpr_ = node;
    }

    public TRPar getRPar()
    {
        return this._rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(this._rPar_ != null)
        {
            this._rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rPar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identificator_)
            + toString(this._lPar_)
            + toString(this._listexpr_)
            + toString(this._rPar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identificator_ == child)
        {
            this._identificator_ = null;
            return;
        }

        if(this._lPar_ == child)
        {
            this._lPar_ = null;
            return;
        }

        if(this._listexpr_ == child)
        {
            this._listexpr_ = null;
            return;
        }

        if(this._rPar_ == child)
        {
            this._rPar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identificator_ == oldChild)
        {
            setIdentificator((TIdentificator) newChild);
            return;
        }

        if(this._lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(this._listexpr_ == oldChild)
        {
            setListexpr((PListexpr) newChild);
            return;
        }

        if(this._rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
