/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class ADiviserExprPlus extends PExprPlus
{
    private PExprPlus _exprPlus_;
    private TDiv _div_;
    private PExprMult _exprMult_;

    public ADiviserExprPlus()
    {
        // Constructor
    }

    public ADiviserExprPlus(
        @SuppressWarnings("hiding") PExprPlus _exprPlus_,
        @SuppressWarnings("hiding") TDiv _div_,
        @SuppressWarnings("hiding") PExprMult _exprMult_)
    {
        // Constructor
        setExprPlus(_exprPlus_);

        setDiv(_div_);

        setExprMult(_exprMult_);

    }

    @Override
    public Object clone()
    {
        return new ADiviserExprPlus(
            cloneNode(this._exprPlus_),
            cloneNode(this._div_),
            cloneNode(this._exprMult_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADiviserExprPlus(this);
    }

    public PExprPlus getExprPlus()
    {
        return this._exprPlus_;
    }

    public void setExprPlus(PExprPlus node)
    {
        if(this._exprPlus_ != null)
        {
            this._exprPlus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprPlus_ = node;
    }

    public TDiv getDiv()
    {
        return this._div_;
    }

    public void setDiv(TDiv node)
    {
        if(this._div_ != null)
        {
            this._div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._div_ = node;
    }

    public PExprMult getExprMult()
    {
        return this._exprMult_;
    }

    public void setExprMult(PExprMult node)
    {
        if(this._exprMult_ != null)
        {
            this._exprMult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprMult_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprPlus_)
            + toString(this._div_)
            + toString(this._exprMult_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprPlus_ == child)
        {
            this._exprPlus_ = null;
            return;
        }

        if(this._div_ == child)
        {
            this._div_ = null;
            return;
        }

        if(this._exprMult_ == child)
        {
            this._exprMult_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprPlus_ == oldChild)
        {
            setExprPlus((PExprPlus) newChild);
            return;
        }

        if(this._div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(this._exprMult_ == oldChild)
        {
            setExprMult((PExprMult) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
