/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class AElementsmultiplesListexpr extends PListexpr
{
    private PExpr _expr_;
    private PListexprChainee _listexprChainee_;

    public AElementsmultiplesListexpr()
    {
        // Constructor
    }

    public AElementsmultiplesListexpr(
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") PListexprChainee _listexprChainee_)
    {
        // Constructor
        setExpr(_expr_);

        setListexprChainee(_listexprChainee_);

    }

    @Override
    public Object clone()
    {
        return new AElementsmultiplesListexpr(
            cloneNode(this._expr_),
            cloneNode(this._listexprChainee_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElementsmultiplesListexpr(this);
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public PListexprChainee getListexprChainee()
    {
        return this._listexprChainee_;
    }

    public void setListexprChainee(PListexprChainee node)
    {
        if(this._listexprChainee_ != null)
        {
            this._listexprChainee_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listexprChainee_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr_)
            + toString(this._listexprChainee_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._listexprChainee_ == child)
        {
            this._listexprChainee_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        if(this._listexprChainee_ == oldChild)
        {
            setListexprChainee((PListexprChainee) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
