/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class AElementsmultiplesList extends PList
{
    private PExpr _expr_;
    private PListChainee _listChainee_;

    public AElementsmultiplesList()
    {
        // Constructor
    }

    public AElementsmultiplesList(
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") PListChainee _listChainee_)
    {
        // Constructor
        setExpr(_expr_);

        setListChainee(_listChainee_);

    }

    @Override
    public Object clone()
    {
        return new AElementsmultiplesList(
            cloneNode(this._expr_),
            cloneNode(this._listChainee_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElementsmultiplesList(this);
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public PListChainee getListChainee()
    {
        return this._listChainee_;
    }

    public void setListChainee(PListChainee node)
    {
        if(this._listChainee_ != null)
        {
            this._listChainee_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listChainee_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr_)
            + toString(this._listChainee_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._listChainee_ == child)
        {
            this._listChainee_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        if(this._listChainee_ == oldChild)
        {
            setListChainee((PListChainee) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
