/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class AEtExprOu extends PExprOu
{
    private PExprOu _exprOu_;
    private TAnd _and_;
    private PExprEt _exprEt_;

    public AEtExprOu()
    {
        // Constructor
    }

    public AEtExprOu(
        @SuppressWarnings("hiding") PExprOu _exprOu_,
        @SuppressWarnings("hiding") TAnd _and_,
        @SuppressWarnings("hiding") PExprEt _exprEt_)
    {
        // Constructor
        setExprOu(_exprOu_);

        setAnd(_and_);

        setExprEt(_exprEt_);

    }

    @Override
    public Object clone()
    {
        return new AEtExprOu(
            cloneNode(this._exprOu_),
            cloneNode(this._and_),
            cloneNode(this._exprEt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEtExprOu(this);
    }

    public PExprOu getExprOu()
    {
        return this._exprOu_;
    }

    public void setExprOu(PExprOu node)
    {
        if(this._exprOu_ != null)
        {
            this._exprOu_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprOu_ = node;
    }

    public TAnd getAnd()
    {
        return this._and_;
    }

    public void setAnd(TAnd node)
    {
        if(this._and_ != null)
        {
            this._and_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._and_ = node;
    }

    public PExprEt getExprEt()
    {
        return this._exprEt_;
    }

    public void setExprEt(PExprEt node)
    {
        if(this._exprEt_ != null)
        {
            this._exprEt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprEt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprOu_)
            + toString(this._and_)
            + toString(this._exprEt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprOu_ == child)
        {
            this._exprOu_ = null;
            return;
        }

        if(this._and_ == child)
        {
            this._and_ = null;
            return;
        }

        if(this._exprEt_ == child)
        {
            this._exprEt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprOu_ == oldChild)
        {
            setExprOu((PExprOu) newChild);
            return;
        }

        if(this._and_ == oldChild)
        {
            setAnd((TAnd) newChild);
            return;
        }

        if(this._exprEt_ == oldChild)
        {
            setExprEt((PExprEt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
