/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class AInstrsiInstr extends PInstr
{
    private PInstrif _instrif_;

    public AInstrsiInstr()
    {
        // Constructor
    }

    public AInstrsiInstr(
        @SuppressWarnings("hiding") PInstrif _instrif_)
    {
        // Constructor
        setInstrif(_instrif_);

    }

    @Override
    public Object clone()
    {
        return new AInstrsiInstr(
            cloneNode(this._instrif_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstrsiInstr(this);
    }

    public PInstrif getInstrif()
    {
        return this._instrif_;
    }

    public void setInstrif(PInstrif node)
    {
        if(this._instrif_ != null)
        {
            this._instrif_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instrif_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instrif_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instrif_ == child)
        {
            this._instrif_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instrif_ == oldChild)
        {
            setInstrif((PInstrif) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
