/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class ALastListedecvarChainee extends PListedecvarChainee
{
    private TComma _comma_;
    private PDecvar _decvar_;

    public ALastListedecvarChainee()
    {
        // Constructor
    }

    public ALastListedecvarChainee(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PDecvar _decvar_)
    {
        // Constructor
        setComma(_comma_);

        setDecvar(_decvar_);

    }

    @Override
    public Object clone()
    {
        return new ALastListedecvarChainee(
            cloneNode(this._comma_),
            cloneNode(this._decvar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALastListedecvarChainee(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PDecvar getDecvar()
    {
        return this._decvar_;
    }

    public void setDecvar(PDecvar node)
    {
        if(this._decvar_ != null)
        {
            this._decvar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decvar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._decvar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._decvar_ == child)
        {
            this._decvar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._decvar_ == oldChild)
        {
            setDecvar((PDecvar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
