/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class AMoinsExprEgal extends PExprEgal
{
    private PExprEgal _exprEgal_;
    private TMinus _minus_;
    private PExprPlus _exprPlus_;

    public AMoinsExprEgal()
    {
        // Constructor
    }

    public AMoinsExprEgal(
        @SuppressWarnings("hiding") PExprEgal _exprEgal_,
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") PExprPlus _exprPlus_)
    {
        // Constructor
        setExprEgal(_exprEgal_);

        setMinus(_minus_);

        setExprPlus(_exprPlus_);

    }

    @Override
    public Object clone()
    {
        return new AMoinsExprEgal(
            cloneNode(this._exprEgal_),
            cloneNode(this._minus_),
            cloneNode(this._exprPlus_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMoinsExprEgal(this);
    }

    public PExprEgal getExprEgal()
    {
        return this._exprEgal_;
    }

    public void setExprEgal(PExprEgal node)
    {
        if(this._exprEgal_ != null)
        {
            this._exprEgal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprEgal_ = node;
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public PExprPlus getExprPlus()
    {
        return this._exprPlus_;
    }

    public void setExprPlus(PExprPlus node)
    {
        if(this._exprPlus_ != null)
        {
            this._exprPlus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprPlus_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprEgal_)
            + toString(this._minus_)
            + toString(this._exprPlus_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprEgal_ == child)
        {
            this._exprEgal_ = null;
            return;
        }

        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._exprPlus_ == child)
        {
            this._exprPlus_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprEgal_ == oldChild)
        {
            setExprEgal((PExprEgal) newChild);
            return;
        }

        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._exprPlus_ == oldChild)
        {
            setExprPlus((PExprPlus) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
