/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleExpr extends PExpr
{
    private PExprOu _exprOu_;

    public ASimpleExpr()
    {
        // Constructor
    }

    public ASimpleExpr(
        @SuppressWarnings("hiding") PExprOu _exprOu_)
    {
        // Constructor
        setExprOu(_exprOu_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleExpr(
            cloneNode(this._exprOu_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleExpr(this);
    }

    public PExprOu getExprOu()
    {
        return this._exprOu_;
    }

    public void setExprOu(PExprOu node)
    {
        if(this._exprOu_ != null)
        {
            this._exprOu_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprOu_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprOu_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprOu_ == child)
        {
            this._exprOu_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprOu_ == oldChild)
        {
            setExprOu((PExprOu) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
