/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleExprMult extends PExprMult
{
    private PExprNo _exprNo_;

    public ASimpleExprMult()
    {
        // Constructor
    }

    public ASimpleExprMult(
        @SuppressWarnings("hiding") PExprNo _exprNo_)
    {
        // Constructor
        setExprNo(_exprNo_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleExprMult(
            cloneNode(this._exprNo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleExprMult(this);
    }

    public PExprNo getExprNo()
    {
        return this._exprNo_;
    }

    public void setExprNo(PExprNo node)
    {
        if(this._exprNo_ != null)
        {
            this._exprNo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprNo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprNo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprNo_ == child)
        {
            this._exprNo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprNo_ == oldChild)
        {
            setExprNo((PExprNo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
