/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleExprEt extends PExprEt
{
    private PExprEgal _exprEgal_;

    public ASimpleExprEt()
    {
        // Constructor
    }

    public ASimpleExprEt(
        @SuppressWarnings("hiding") PExprEgal _exprEgal_)
    {
        // Constructor
        setExprEgal(_exprEgal_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleExprEt(
            cloneNode(this._exprEgal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleExprEt(this);
    }

    public PExprEgal getExprEgal()
    {
        return this._exprEgal_;
    }

    public void setExprEgal(PExprEgal node)
    {
        if(this._exprEgal_ != null)
        {
            this._exprEgal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprEgal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprEgal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprEgal_ == child)
        {
            this._exprEgal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprEgal_ == oldChild)
        {
            setExprEgal((PExprEgal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
