/* This file was generated by SableCC (http://www.sablecc.org/). */

package lcompil.node;

import lcompil.analysis.*;

@SuppressWarnings("nls")
public final class AVarsimpleVar extends PVar
{
    private TIdentificator _identificator_;

    public AVarsimpleVar()
    {
        // Constructor
    }

    public AVarsimpleVar(
        @SuppressWarnings("hiding") TIdentificator _identificator_)
    {
        // Constructor
        setIdentificator(_identificator_);

    }

    @Override
    public Object clone()
    {
        return new AVarsimpleVar(
            cloneNode(this._identificator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarsimpleVar(this);
    }

    public TIdentificator getIdentificator()
    {
        return this._identificator_;
    }

    public void setIdentificator(TIdentificator node)
    {
        if(this._identificator_ != null)
        {
            this._identificator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identificator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identificator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identificator_ == child)
        {
            this._identificator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identificator_ == oldChild)
        {
            setIdentificator((TIdentificator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
